version: "3"

services:
  linkstack:
    hostname: "linkstack"
    image: "ghcr.io/hashim-k/linkstack:main"
    environment:
      TZ: ${TZ}
      SERVER_ADMIN: ${SERVER_ADMIN}
      HTTP_SERVER_NAME: ${HTTP_SERVER_NAME}
      HTTPS_SERVER_NAME: ${HTTPS_SERVER_NAME}
      LOG_LEVEL: ${LOG_LEVEL}
      PHP_MEMORY_LIMIT: ${PHP_MEMORY_LIMIT}
      UPLOAD_MAX_FILESIZE: ${UPLOAD_MAX_FILESIZE}
    volumes:
      - ./htdocs:/htdocs
    ports:
      - "${LINKSTACK_HTTP_PORT}:80"
      - "${LINKSTACK_HTTPS_PORT}:443"
    restart: unless-stopped
    user: "apache:apache"
    depends_on:
      - mysql
    links:
      - mysql

  mysql:
    image: mysql:8
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
    ports:
      - "${MYSQL_PORT}:3306"
