name: Docker Image CI

on:
  push:
    branches:
      - main
    tags:
      - 'v*'
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

  deploy:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to GitHub Container Registry (GHCR)
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - id: string
        uses: ASzc/change-string-case-action@v1
        with:
          string: ${{ github.repository }}

      - id: sanitize_tag
        name: Sanitize image tag
        run: echo tag=${raw_tag//\//-} >> $GITHUB_OUTPUT
        env:
          raw_tag: ${{ github.ref_name }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: |
            ghcr.io/${{ steps.string.outputs.lowercase }}:${{ steps.sanitize_tag.outputs.tag }}
            ghcr.io/${{ steps.string.outputs.lowercase }}:${{ steps.sanitize_tag.outputs.tag }}-${{ github.sha }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
